### ISSUE TITLE
Is it possible to run deepsort tracker with osnet?

### ISSUE THREAD

**Issue by youngjae-avikus** [ml6team/deepstream-python#12]
Hi! Can I replace the cosine_metric model provided by deepsort based on the osnet provided?

**Comment by Joxis** [comment]
The re-identification model used by DeepSORT is specified here: https://github.com/ml6team/deepstream-python/blob/master/deepstream/configs/trackers/DeepSORT_config.yml#L74

You could try changing that (and related settings). I have not tried it myself yet. 
The re-identification pipeline in this repository uses OSNet as a secondary model, in addition to the DeepSORT mars-small128.
