### ISSUE TITLE
Make it not 6.1 specific

### ISSUE THREAD

**Issue by GerardNL** [ml6team/deepstream-python#15]
I'm still learning docker, deepstream etc, so maybe it's very obvious or not relevant but...

In these 3 files:
deepstream/app/config.py
deepstream/configs/pgies/pgie.txt
deepstream/configs/pgies/segmentation.txt

there is a reference to 
/opt/nvidia/deepstream/**deepstream-6.1**

but if that would be changed to:
/opt/nvidia/deepstream/**deepstream**
(which is a symbolic link to the 6.1 or 6.2 etc)

Then (most/all of) the script would work also with 6.2 (or 6.0)

**Comment by GerardNL** [comment]
Hi Joxis,

Yes, with those changes, it worked for me in 6.2.

There is the unrelated issue with the additional libraries that are no longer default in 6.2 that need to be installed:
`RUN bash /opt/nvidia/deepstream/deepstream/user_additional_install.sh`
(See other ticket)

But I think this will make it slightly less version specific without affecting anything else, so I think it's worth it.

Thanks in advance as I appreciate the efforts that have been put in this repository. As I'm learning DS, it helped.

**Comment by Joxis** [comment]
I will take up your suggested changes in the other ticket and close this one so it's easier to track

**Comment by GerardNL** [comment]
As you want. The items are related, but also somewhat different, so I wasn't sure what would be better.
