### ISSUE TITLE
Incorrect reference to engine?

### ISSUE THREAD

**Issue by GerardNL** [ml6team/deepstream-python#16]
I'm not quite sure, but I think there is an error in line 65 of deepstream/configs/pgies/pgie.txt

It reads:
model-engine-file=**..**/opt/nvidia/deepstream/deepstream-6.1/samples/models/Primary_Detector/resnet10.caffemodel_b1_gpu0_fp16.engine

which should probably be:
model-engine-file=/opt/nvidia/deepstream/deepstream-/samples/models/Primary_Detector/resnet10.caffemodel_b1_gpu0_fp16.engine

However, when I try this with DS 6.2 and still new to DS, I don't have this engine file there either. So I'm a bit confused, but based on other lines in that same file, it seems likely to be a typo?

**Comment by Joxis** [comment]
This is not a typo but a shortcoming of Deepstream itself. I believe point 1 and 2 of the [Caveats section](https://github.com/ml6team/deepstream-python#caveats) cover your points.

**Comment by GerardNL** [comment]
The warnings thrown out by DS are still a bit confusing at times and doesn't help a novice. I think the code works despite the error. So let's close it.
