### ISSUE TITLE
error: 'MODE_NONE' was not declared in this scope

### ISSUE THREAD

**Issue by flmello** [ml6team/deepstream-python#18]
Hardware Platform:  RTX A4000
NVIDIA-SMI 535.54.03
CUDA Version: 12.2
SO: Ubuntu 22.04
Python: 3.10.6

I am trying to create the docker image from Dockerfile, ans I kept the original version from the dockerfile (FROM nvcr.io/nvidia/deepstream:6.1-devel). It seems that when compiling the python bindings, the is an error:

```
opt/nvidia/deepstream/deepstream/sources/deepstream_python_apps/bindings/src/bindnvosd.cpp:36:37:
error: 'MODE_NONE' was not declared in this scope; did you mean
'pydsdoc::NvOSD::NvOSD_Mode::MODE_NONE'?
   36 |                 .value("MODE_NONE", MODE_NONE,
pydsdoc::NvOSD::NvOSD_Mode::MODE_NONE)
      |                                     ^~~~~~~~~
      |
pydsdoc::NvOSD::NvOSD_Mode::MODE_NONE
```

The complete log is in this link: https://drive.google.com/file/d/1k8p9qYR1NwJagE_0manqSacghIO_KIek/view?usp=sharing.

How to override this?

**Comment by Joxis** [comment]
This seems to be an issue with an update of the repository from NVIDIA. You can try out the solution suggested in this post: https://forums.developer.nvidia.com/t/error-mode-none-was-not-declared-in-this-scope-did-you-mean-pydsdoc-mode-none/241903/4

You can add the git checkout statement after the following line https://github.com/ml6team/deepstream-python/blob/master/deepstream/Dockerfile#L17

**Comment by flmello** [comment]
So I added this after "git submodule update --init":

git checkout v1.1.2  

... and it compiled. Thanks!
