### ISSUE TITLE
How to implement and integrate custom analytics functions in DeepStream

### ISSUE THREAD

**Issue by HtutLynn** [ml6team/deepstream-python#3]
Thanks for the great repo! Hi, I am a beginner in DeepStream and learning on how to convert pytorch-based pipeline to DeepStream based pipeline to improve runtime performance on Jetson devices. I want to implement functions such as line-cross counting similar to [this video](https://youtu.be/gs9cy2XfCBA) and also want to stream outputs to websocket server via kafka or directly. I am struggling to integrate these functions to DeepStream app and kinda lost on where to start right now. Can you please guide me on this? Thanks in advance!

**Comment by Joxis** [comment]
Hi! Glad you like the repository. 

Did you take a look at the [`Gst-nvdsanalytics`](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvdsanalytics.html) plugin already?

> This plugin performs analytics on metadata attached by nvinfer (primary detector) and nvtracker. Analytics refer to Region of Interest (ROI) Filtering, Overcrowding Detection, Direction Detection and Line Crossing. 

Incorporating this plugin into the base (detection & tracking) pipeline should allow you to gather the required statistics. You can find an example config on the [NVIDIA-AI-IOT/deepstream_python_apps](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/blob/master/apps/deepstream-nvdsanalytics/config_nvdsanalytics.txt) repository.

The Kafka connectivity can be achieved with the [`Gst-nvmsgconv`](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvmsgconv.html) and [`Gst-nvmsgbroker`](https://docs.nvidia.com/metropolis/deepstream/dev-guide/text/DS_plugin_gst-nvmsgbroker.html) plugins. An example from NVIDIA can be found [here](https://github.com/NVIDIA-AI-IOT/deepstream_python_apps/tree/master/apps/deepstream-test4). Again, these could be incorporated into the base pipeline.

I hope that helps!
