### ISSUE TITLE
Git LFS quota.

### ISSUE THREAD

**Issue by nikulin-94** [ml6team/deepstream-python#4]
Hi! I have this problems:
 
Git LFS: (0 of 8 files) 0 B / 246.55 MB                                                                                                                                                                   
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/ml6team/deepstream-python.git/info/lfs'

You can help me?

**Comment by Joxis** [comment]
I will make the LFS-managed files available via another method and get back to you ASAP. Thanks for reporting this!

**Comment by Joxis** [comment]
@nikulin-94 You can find a zip file containing the `data` folder here: https://drive.google.com/file/d/1xu22FTWw0Cx4bOgrKUVtZU1VMHt3Oml8/view?usp=sharing

You may delete the current folder and put this one in place. You should then have all required files. Let me know if you still encounter problems.

I will also update the documentation.

**Comment by nikulin-94** [comment]
@Joxis thanks for the help.
However, I'm having a problem while building the container:
```-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:93 (message):
  Missing libnvds_osd.so at
  /opt/nvidia/deepstream/deepstream-6.1/lib/libnvds_osd.so

  please make sure that deepstream is installed
Call Stack (most recent call first):
  CMakeLists.txt:103 (add_ds_lib)


-- Configuring incomplete, errors occurred!
See also "/opt/nvidia/deepstream/deepstream/sources/apps/deepstream_python_apps/bindings/build/CMakeFiles/CMakeOutput.log".
The command '/bin/sh -c cd /opt/nvidia/deepstream/deepstream/sources/apps/     && git clone https://github.com/NVIDIA-AI-IOT/deepstream_python_apps.git     && cd deepstream_python_apps     && git submodule update --init     && apt-get install --reinstall ca-certificates     && cd 3rdparty/gst-python/     && ./autogen.sh     && make     && make install     && cd ../../bindings     && mkdir build     && cd build     && cmake ..     && make     && pip3 install ./pyds-1.1.1-py3-none*.whl' returned a non-zero code: 1
```

**Comment by Joxis** [comment]
@nikulin-94 Are you using the provided Docker image?

**Comment by nikulin-94** [comment]
@Joxis yes. The error occurs when executing the block:
```
# Compile Python bindings
....
  row 27: && cmake .. \
```
